include config.make
ROOT=$(DESTDIR)$(prefix)
SAMPLES=$(ROOT)/examples/lablgtk2

all:
	cp README $(ROOT)/Lablgtk.txt
	cp README.win32 $(ROOT)/Lablgtk-install.txt
	cp CHANGES $(ROOT)/Lablgtk-changes.txt
	for i in . glade rsvg text canvas sourceview; do \
	  mkdir -p $(SAMPLES)/$$i; \
	  (cd examples/$$i; cp * $(SAMPLES)/$$i); done
