open GMain

(* This program is generated by lablglade *)

class my_class =
   let window1 = new GWindow.window in
   let fixed1 = new GPack.fixed packing:window1#add in
   let button1 = new GButton.button label:"button1" width:47 height:22 packing:fixed1#add in
   let _ = button1#misc#set x:56 y:56 in
object (self)
   val window1 = window1
   val fixed1 = fixed1
   val button1 = button1
   method show () = 
   window1#show ();
initializer 
   (* signal handlers here *)
   let on_button1_clicked () = prerr_endline "hello"
   in
   button1#connect#clicked callback:on_button1_clicked;
()
end

let main () =
   let my_win = new my_class in
   my_win#show ();
   Main.main () 

let _ = main ()