open GMain

(* This program is generated by lablglade *)

let main () =
   let window1 = new GWindow.window in
   let fixed1 = new GPack.fixed packing:window1#add in
   let button1 = new GButton.button label:"Push!" width:47 height:22 packing:fixed1#add in
   button1#misc#set x:24 y:40;
   let entry1 = new GEdit.entry text:"0" width:158 height:22 packing:fixed1#add in
   entry1#misc#set x:96 y:40;
   let drawingarea1 = new GMisc.drawing_area width:384 height:176 packing:fixed1#add in
   drawingarea1#misc#set x:16 y:104;
   window1#show ();
   Main.main () 

let _ = main ()