# $Id$
# Makefile for lablgtk.

EXE = .exe
TARGETS = var2conv var2def lablgtk$(EXE) lablgtk_t$(EXE) \
	lablgtkrun$(EXE)

all: $(TARGETS)

opt: lablgtkopt

config.make:
	cp config.make.nt config.make

nothing:

CAMLC = ocamlc
CAMLOPT = ocamlopt
COMPILER = $(CAMLC) $(MLFLAGS) -w s -modern -c
LINKER = $(CAMLC) $(MLFLAGS)
COMPOPT = $(CAMLOPT) $(MLFLAGS) -w s -modern -c
LINKOPT = $(CAMLOPT) $(MLFLAGS)

TOPLEVEL = ocamlmktop $(MLFLAGS)
### How to invoke the librarian
MKLIB=lib /nologo /debugtype:CV /out:

!include config.make

CFLAGS = -O -DGTK_NO_CHECK_CASTS -DGTK_DISABLE_COMPAT_H $(GTKCFLAGS)
LDFLAGS = $(GTKLIBS)

THFLAGS = -thread
THLIBS = unix.cma threads.cma
THLDFLAGS = -lthreads -lunix

!if $(USE_CC) == 1
CCOMPILER = $(CC) -c -I$(LABLLIB) $(CFLAGS)
!else
CCOMPILER = ocamlc -c -ccopt "$(CFLAGS)"
!endif

!if $(USE_GL) == 1
MLFLAGS = $(MLFLAGS) -I $(LABLLIB)/lablGL
GLLINK = -I $(LABLLIB)/lablGL lablgl.cma \
	-cclib "-lgtkgl -L$(LABLLIB)/lablGL -llablgl -l$(MESA)GL -l$(MESA)GLU"
GLMLOBJS = glGtk.cmo
GLCOBJS = ml_gtkgl.obj
!endif

# Rules
.SUFFIXES: .ml .mli .cmo .cmi .cmx .c .obj .var .h .opt .def
.c.obj:
	$(CCOMPILER) $<
.ml.cmo:
	$(COMPILER) $<
.mli.cmi:
	$(COMPILER) $<
.ml.cmx:
	$(COMPOPT) $<
.var.h:
	ocamlrun ./var2def < $< > $@
.var.c:
	ocamlrun ./var2conv < $< > $@

# Targets
COBJS = ml_gtk.obj ml_gdk.obj ml_glib.obj wrappers.obj $(GLCOBJS)
OLDMLOBJS = misc.cmo glib.cmo gdk.cmo gtk.cmo gdkObj.cmo gtkObj.cmo gtkExt.cmo
MLOBJS = misc.cmo glib.cmo gdk.cmo gdkEvent.cmo gdkKeysyms.cmo \
	gtk.cmo gtkArgv.cmo gtkSignal.cmo \
	gtkData.cmo gtkBase.cmo gtkPack.cmo gtkButton.cmo \
	gtkMenu.cmo gtkMisc.cmo gtkWindow.cmo gtkTree.cmo gtkList.cmo \
	gtkFrame.cmo gtkEdit.cmo gtkRange.cmo gtkMain.cmo gtkNew.cmo \
	gdkObj.cmo \
	gObj.cmo gMain.cmo gData.cmo gContainer.cmo gPack.cmo gButton.cmo \
	gMenu.cmo gMisc.cmo gWindow.cmo gTree.cmo gList.cmo gFrame.cmo \
	gEdit.cmo gPix.cmo gRange.cmo gUtil.cmo $(GLMLOBJS)
THOBJS = gtkThread.cmo threadObj.cmo

lablgtk$(EXE): liblablgtk.lib lablgtk.cma gtkInit.cmo
	$(TOPLEVEL) -o $@ -custom liblablgtk.lib $(GTKLIBS) \
		$(GLLINK) lablgtk.cma gtkInit.cmo

lablgtkrun$(EXE): liblablgtk.lib lablgtk.cma
	$(LINKER) -o $@ -make-runtime $(GLLINK) lablgtk.cma \
		-cclib "-L. -llablgtk $(LDFLAGS)"

lablgtkopt: liblablgtk.lib lablgtk.cmxa

liblablgtk.lib: $(COBJS)
	$(MKLIB)$@ $(COBJS)

lablgtk.cma: $(MLOBJS)
	$(LINKER) -a -o $@ $(MLOBJS)

lablgtk.cmxa: $(MLOBJS:.cmo=.cmx)
	$(LINKOPT) -a -o $@ $(MLOBJS:.cmo=.cmx)

gtkThread.cmo: gtkThread.ml
	$(COMPILER) $(THFLAGS) gtkThread.ml

threadObj.cmo: threadObj.ml
	$(COMPILER) $(THFLAGS) threadObj.ml

gtkThread.cmx: gtkThread.ml
	$(COMPOPT) $(THFLAGS) gtkThread.ml

threadObj.cmx: threadObj.ml
	$(COMPOPT) $(THFLAGS) threadObj.ml

lablgtk_t$(EXE): liblablgtk.lib lablgtk.cma $(THOBJS) gtkInit.cmo
	$(TOPLEVEL) $(THFLAGS) -o $@ -custom \
		-cclib "-L. -llablgtk $(LDFLAGS) $(THLDFLAGS)" \
		$(GLLINK) $(THLIBS) lablgtk.cma $(THOBJS) gtkInit.cmo

var2conv: var2conv.cmo
	$(LINKER) -o $@ var2conv.cmo
	rm -f *_tags.c

var2def: var2def.cmo
	$(LINKER) -o $@ var2def.cmo
	rm -f *_tags.h

clean:
	rm -f *.cm* *.obj *.lib *_tags.[ch] $(TARGETS)

depend .depend:
	ocamldep *.ml *.mli > .depend

ml_gtk.obj: gtk_tags.c gtk_tags.h ml_gtk.h ml_gdk.h wrappers.h
ml_gdk.obj: gdk_tags.c gdk_tags.h ml_gdk.h wrappers.h
ml_gtkgl.obj: gtkgl_tags.c gtkgl_tags.h ml_gtk.h ml_gdk.h wrappers.h

!include .depend
