open GMain

(* This program is generated by lablglade *)

let main () =
   let window1 = new GWindow.window in
   let fixed1 = new GPack.fixed packing:window1#add in
   let button1 = new GButton.button label:"button1" width:47 height:22 packing:fixed1#add in
   button1#misc#set x:24 y:8;
   let entry1 = new GEdit.entry text:"" width:158 height:22 packing:fixed1#add in
   entry1#misc#set x:24 y:40;
   let drawingarea1 = new GMisc.drawing_area width:368 height:200 packing:fixed1#add in
   drawingarea1#misc#set x:16 y:80;
   window1#show ();
   Main.main () 

let _ = main ()