open GMain

(* This program is generated by lablglade *)

class my_class =
   let window1 = new GWindow.window in
   let vbox1 = new GPack.box `VERTICAL packing:window1#add in
   let fixed1 = new GPack.fixed packing:vbox1#add in
   let button1 = new GButton.button label:"button1" width:47 height:22 packing:fixed1#add in
   let _ = button1#misc#set x:16 y:24 in
   let entry1 = new GEdit.entry text:"" width:158 height:22 packing:fixed1#add in
   let _ = entry1#misc#set x:200 y:32 in
   let drawingarea1 = new GMisc.drawing_area packing:vbox1#add in
object (self)
   val window1 = window1
   val vbox1 = vbox1
   val fixed1 = fixed1
   val button1 = button1
   val entry1 = entry1
   val drawingarea1 = drawingarea1
   method show () = 
   window1#show ();
end

let main () =
   let my_win = new my_class in
   my_win#show ();
   Main.main () 

let _ = main ()